test:
    image: python:3.6
    script:
        - pip3 install -r requirements.txt
        - cd src
        - cp appstore/settings/local.sample.env appstore/settings/local.env
        - python3 manage.py test